# do not log the following
SetEnvIf Request_URI ^/fpm-ping is-nolog=1

# Define an access log for VirtualHosts that don't define their own logfile
CustomLog /docker.stdout vhost_combined env=!is-nolog